comments:
    resource: '../src/Comments/Presentation/Resources/config/routes/annotations.yaml'

task:
    resource: '../src/Tasks/Presentation/Resources/config/routes/annotations.yaml'

users:
    resource: '../src/Users/Presentation/Resources/config/routes/annotations.yaml'

statistics:
    resource: '../src/Statistics/Presentation/Resources/config/routes/annotations.yaml'
