framework:
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/src/Core/Presentation/Resources/translations'
        paths:
            - '%kernel.project_dir%/src/Core/Presentation/Resources/translations'
        fallbacks:
            - en
